// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";

export class InitializePoll {
  static encode(message: InitializePoll, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.trxHash);

    writer.uint32(16);
    writer.uint64(message.pollId);

    writer.uint32(26);
    writer.string(message.description);

    writer.uint32(32);
    writer.uint64(message.pollStart);

    writer.uint32(40);
    writer.uint64(message.pollEnd);

    writer.uint32(50);
    writer.string(message.acctSigner);

    writer.uint32(58);
    writer.string(message.acctPoll);
  }

  static decode(reader: Reader, length: i32): InitializePoll {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new InitializePoll();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.trxHash = reader.string();
          break;

        case 2:
          message.pollId = reader.uint64();
          break;

        case 3:
          message.description = reader.string();
          break;

        case 4:
          message.pollStart = reader.uint64();
          break;

        case 5:
          message.pollEnd = reader.uint64();
          break;

        case 6:
          message.acctSigner = reader.string();
          break;

        case 7:
          message.acctPoll = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  trxHash: string;
  pollId: u64;
  description: string;
  pollStart: u64;
  pollEnd: u64;
  acctSigner: string;
  acctPoll: string;

  constructor(
    trxHash: string = "",
    pollId: u64 = 0,
    description: string = "",
    pollStart: u64 = 0,
    pollEnd: u64 = 0,
    acctSigner: string = "",
    acctPoll: string = ""
  ) {
    this.trxHash = trxHash;
    this.pollId = pollId;
    this.description = description;
    this.pollStart = pollStart;
    this.pollEnd = pollEnd;
    this.acctSigner = acctSigner;
    this.acctPoll = acctPoll;
  }
}
